# Exercise 3: Numpy

Perform the follwing tasks:


In [2]:
#3.1: import the numpy library
import numpy as np
import numpy.linalg as npla

In [30]:
#3.2: create a random 10x10 array named A
A=np.random.rand(10,10)
A

array([[0.36269156, 0.29968411, 0.61858834, 0.22791048, 0.71229163,
        0.01116571, 0.1825496 , 0.82650928, 0.15059222, 0.47312146],
       [0.09051248, 0.44595976, 0.68748518, 0.6531811 , 0.46856179,
        0.0357586 , 0.12668636, 0.59906852, 0.480236  , 0.84123818],
       [0.57206183, 0.26600232, 0.37824072, 0.13345255, 0.32076487,
        0.62664444, 0.36969496, 0.8259235 , 0.36202127, 0.46519025],
       [0.71274443, 0.64448179, 0.2927055 , 0.12929771, 0.97117038,
        0.13853132, 0.01045711, 0.48906466, 0.54967705, 0.52831529],
       [0.17161971, 0.72533763, 0.44641621, 0.45164932, 0.24269135,
        0.82799603, 0.33729734, 0.88364659, 0.57842246, 0.22306571],
       [0.26259081, 0.64826312, 0.70834007, 0.17768521, 0.38185124,
        0.04940465, 0.71980857, 0.11936053, 0.03803513, 0.41575611],
       [0.89204359, 0.95623626, 0.16042985, 0.1219822 , 0.7524815 ,
        0.82021542, 0.57159949, 0.60179852, 0.90444736, 0.56243972],
       [0.5160449 , 0.43758313, 0.3294149

In [31]:
#3.3: return only the odd rows of A
A[::2]

array([[0.36269156, 0.29968411, 0.61858834, 0.22791048, 0.71229163,
        0.01116571, 0.1825496 , 0.82650928, 0.15059222, 0.47312146],
       [0.57206183, 0.26600232, 0.37824072, 0.13345255, 0.32076487,
        0.62664444, 0.36969496, 0.8259235 , 0.36202127, 0.46519025],
       [0.17161971, 0.72533763, 0.44641621, 0.45164932, 0.24269135,
        0.82799603, 0.33729734, 0.88364659, 0.57842246, 0.22306571],
       [0.89204359, 0.95623626, 0.16042985, 0.1219822 , 0.7524815 ,
        0.82021542, 0.57159949, 0.60179852, 0.90444736, 0.56243972],
       [0.25665145, 0.0394069 , 0.18192975, 0.45517693, 0.25299976,
        0.89596352, 0.56580261, 0.82239643, 0.34676023, 0.67849624]])

In [32]:
#3.4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[2.12639837, 2.06335409, 1.81179444, 2.09434299, 1.82537153,
        1.47320623, 2.28633347, 1.77706986, 1.66762369, 1.52534106],
       [2.06335409, 2.64042369, 1.79712625, 2.10033946, 2.12176883,
        1.62729931, 2.41949378, 2.04324949, 1.91543043, 1.81643134],
       [1.81179444, 1.79712625, 2.2207463 , 1.95802084, 2.28464192,
        1.33960438, 2.89440579, 2.28067895, 2.2590399 , 2.00099165],
       [2.09434299, 2.10033946, 1.95802084, 2.80867413, 2.00073367,
        1.51940943, 3.25381506, 2.02033688, 1.64744175, 2.15852642],
       [1.82537153, 2.12176883, 2.28464192, 2.00073367, 2.9822507 ,
        1.50832348, 3.20834381, 2.64731224, 2.43215625, 2.10761893],
       [1.47320623, 1.62729931, 1.33960438, 1.51940943, 1.50832348,
        1.87743902, 2.06881866, 1.27252891, 1.24426901, 1.58923165],
       [2.28633347, 2.41949378, 2.89440579, 3.25381506, 3.20834381,
        2.06881866, 4.81297959, 3.11725399, 2.79016683, 3.16802117],
       [1.77706986, 2.04324949, 2.2806789

In [33]:
#3.5: compute the matrix inverse of A
npla.inv(A)

array([[ -0.20268998,  -2.45450361,  -2.25241152,   2.8818266 ,
         -0.38709103,   1.2149029 ,  -2.52695066,   2.39334612,
          1.71819254,   0.96985985],
       [ 11.15704973,  -0.02725043,  -8.54289863,  -9.82141322,
         -0.26588624,  -4.07398549,   7.56272389,  -1.29188733,
         -0.65873079,   3.45464088],
       [-11.543818  ,   1.04200705,  10.58972351,   9.02154577,
          1.39178909,   4.25850337,  -7.40257377,   0.07505086,
         -1.28825049,  -3.23847974],
       [ -1.02317853,  -3.02946061,  -5.30951493,   5.04492619,
          0.74662078,   2.11216528,  -4.43902456,   3.32760272,
          3.77688093,   0.7678059 ],
       [ -5.4362436 ,  -0.31819762,   3.59870619,   5.97309723,
          0.83447916,   2.18391457,  -3.73556926,  -0.16126956,
          0.63758615,  -2.01782097],
       [ -5.44630477,   0.15123642,   4.74146648,   4.15666057,
          1.4191187 ,   1.33439736,  -3.17897003,  -1.01904242,
          0.11593764,  -1.10560006],
       [ -

In [37]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
print(A)
print('------------')
print(np.where(A<0.5,A,A/2))
print('------------')
A[A>0.5]/=2
print(A)

[[0.36269156 0.29968411 0.61858834 0.22791048 0.71229163 0.01116571
  0.1825496  0.82650928 0.15059222 0.47312146]
 [0.09051248 0.44595976 0.68748518 0.6531811  0.46856179 0.0357586
  0.12668636 0.59906852 0.480236   0.84123818]
 [0.57206183 0.26600232 0.37824072 0.13345255 0.32076487 0.62664444
  0.36969496 0.8259235  0.36202127 0.46519025]
 [0.71274443 0.64448179 0.2927055  0.12929771 0.97117038 0.13853132
  0.01045711 0.48906466 0.54967705 0.52831529]
 [0.17161971 0.72533763 0.44641621 0.45164932 0.24269135 0.82799603
  0.33729734 0.88364659 0.57842246 0.22306571]
 [0.26259081 0.64826312 0.70834007 0.17768521 0.38185124 0.04940465
  0.71980857 0.11936053 0.03803513 0.41575611]
 [0.89204359 0.95623626 0.16042985 0.1219822  0.7524815  0.82021542
  0.57159949 0.60179852 0.90444736 0.56243972]
 [0.5160449  0.43758313 0.32941497 0.37470549 0.06945693 0.5454355
  0.28834421 0.93309744 0.78433077 0.36368622]
 [0.25665145 0.0394069  0.18192975 0.45517693 0.25299976 0.89596352
  0.56580261 0